development:
  adapter: postgresql
  encoding: unicode
  database: d3tc7jbg7b9ps5
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: d3tc7jbg7b9ps5
  pool: 5
  username: 
  password: 

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  database: d3tc7jbg7b9ps5
  pool: 5
  username: 
  password: 