development:
  adapter: postgresql
  encoding: unicode
  database: d3tc7jbg7b9ps5
  pool: 5
  username: postgres
  password: pass

test:
  adapter: postgresql
  encoding: unicode
  database: d3tc7jbg7b9ps5
  pool: 5
  username: postgres
  password: pass

production:
  adapter: postgresql
  encoding: unicode
  database: d3tc7jbg7b9ps5
  pool: 5
  username: postgres
  password: pass