development:
  adapter: postgresql
  encoding: unicode
  database: url_shortener_development
  pool: 5
  username: postgres
  password: pass

test:
  adapter: postgresql
  encoding: unicode
  database: url_shortener_development
  pool: 5
  username: postgres
  password: pass

production:
  adapter: postgresql
  encoding: unicode
  database: url_shortener_production
  pool: 5
  username: postgres
  password: pass